"""V4 tables: capability, webhooks, custom fields, approvals, decisions, splits, ledger, history

Revision ID: 5132d7124e47
Revises: c08b2cc98b13
Create Date: 2026-09-27 00:55:41.303270

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5132d7124e47'
down_revision: Union[str, None] = 'c08b2cc98b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_type', sa.String(length=100), nullable=True),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_version', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('causation_id', sa.String(length=64), nullable=True),
    sa.Column('producer', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_domain_events_event_id'))
    )
    op.create_index('ix_deh_agg', 'domain_events', ['tenant_id', 'aggregate_type', 'aggregate_id'], unique=False)
    op.create_index(op.f('ix_domain_events_tenant_id'), 'domain_events', ['tenant_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_reference', sa.String(length=200), nullable=True),
    sa.Column('approver_role_required', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approval_requests_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_tenant_id'), 'approval_requests', ['tenant_id'], unique=False)
    op.create_index('ix_approvals_status', 'approval_requests', ['tenant_id', 'status'], unique=False)
    op.create_table('capability_grants',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('grantee_type', sa.String(length=30), nullable=False),
    sa.Column('grantee_id', sa.String(length=200), nullable=False),
    sa.Column('resource_scope', sa.String(length=100), nullable=False),
    sa.Column('action_scope', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_by', sa.String(length=120), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_capability_grants_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_grants'))
    )
    op.create_index('ix_cap_grants_lookup', 'capability_grants', ['tenant_id', 'grantee_type', 'grantee_id'], unique=False)
    op.create_index(op.f('ix_capability_grants_tenant_id'), 'capability_grants', ['tenant_id'], unique=False)
    op.create_table('commission_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('party_role', sa.String(length=40), nullable=False),
    sa.Column('party_id', sa.String(length=120), nullable=True),
    sa.Column('share_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_commission_splits_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_splits')),
    sa.UniqueConstraint('deal_id', 'party_role', 'party_id', name='uq_split_party')
    )
    op.create_index(op.f('ix_commission_splits_deal_id'), 'commission_splits', ['deal_id'], unique=False)
    op.create_index(op.f('ix_commission_splits_tenant_id'), 'commission_splits', ['tenant_id'], unique=False)
    op.create_table('custom_field_definitions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_custom_field_definitions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_definitions')),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'field_key', name='uq_cfd_key')
    )
    op.create_index(op.f('ix_custom_field_definitions_tenant_id'), 'custom_field_definitions', ['tenant_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_custom_field_values_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_values')),
    sa.UniqueConstraint('tenant_id', 'entity_type', 'entity_id', 'field_key', name='uq_cfv_key')
    )
    op.create_index('ix_cfv_entity', 'custom_field_values', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_tenant_id'), 'custom_field_values', ['tenant_id'], unique=False)
    op.create_table('decisions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optimization_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=True),
    sa.Column('ai_execution_id', sa.UUID(), nullable=True),
    sa.Column('selected_option', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_decisions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_subject', 'decisions', ['tenant_id', 'action'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_table('inventory_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=True),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('tx_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_inventory_ledger_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_ledger'))
    )
    op.create_index('ix_inv_ledger_unit', 'inventory_ledger', ['tenant_id', 'asset_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_asset_id'), 'inventory_ledger', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inventory_ledger_tenant_id'), 'inventory_ledger', ['tenant_id'], unique=False)
    op.create_table('webhook_destinations',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('allowlist_status', sa.String(length=30), nullable=False),
    sa.Column('verification_token', sa.String(length=120), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_webhook_destinations_owner_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhook_destinations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_destinations')),
    sa.UniqueConstraint('tenant_id', 'url', name='uq_webhook_dest_url')
    )
    op.create_index(op.f('ix_webhook_destinations_tenant_id'), 'webhook_destinations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_destinations_tenant_id'), table_name='webhook_destinations')
    op.drop_table('webhook_destinations')
    op.drop_index(op.f('ix_inventory_ledger_tenant_id'), table_name='inventory_ledger')
    op.drop_index(op.f('ix_inventory_ledger_asset_id'), table_name='inventory_ledger')
    op.drop_index('ix_inv_ledger_unit', table_name='inventory_ledger')
    op.drop_table('inventory_ledger')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index('ix_decisions_subject', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_custom_field_values_tenant_id'), table_name='custom_field_values')
    op.drop_index('ix_cfv_entity', table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_custom_field_definitions_tenant_id'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_index(op.f('ix_commission_splits_tenant_id'), table_name='commission_splits')
    op.drop_index(op.f('ix_commission_splits_deal_id'), table_name='commission_splits')
    op.drop_table('commission_splits')
    op.drop_index(op.f('ix_capability_grants_tenant_id'), table_name='capability_grants')
    op.drop_index('ix_cap_grants_lookup', table_name='capability_grants')
    op.drop_table('capability_grants')
    op.drop_index('ix_approvals_status', table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_tenant_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_domain_events_tenant_id'), table_name='domain_events')
    op.drop_index('ix_deh_agg', table_name='domain_events')
    op.drop_table('domain_events')
    # ### end Alembic commands ###
