"""V4-2: claims, signal engine, projection registry

Revision ID: 52ba6440e17d
Revises: f6c85dga4455
Create Date: 2026-09-27 01:45:58.253265

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52ba6440e17d'
down_revision: Union[str, None] = 'f6c85dga4455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('truth_status', sa.String(length=20), nullable=False),
    sa.Column('assertion_type', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_claims_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    op.create_index('ix_claims_entity_field', 'claims', ['tenant_id', 'entity_type', 'entity_id', 'field'], unique=False)
    op.create_index(op.f('ix_claims_entity_id'), 'claims', ['entity_id'], unique=False)
    op.create_index('ix_claims_status', 'claims', ['truth_status'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_table('projection_registry',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('projection_name', sa.String(length=120), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('projection_type', sa.String(length=40), nullable=False),
    sa.Column('max_staleness_ms', sa.Integer(), nullable=False),
    sa.Column('consumer_cursor', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_lag_ms', sa.Integer(), nullable=False),
    sa.Column('critical_path', sa.Boolean(), nullable=False),
    sa.Column('degraded_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projection_registry_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projection_registry')),
    sa.UniqueConstraint('tenant_id', 'projection_name', 'environment', name='uq_projection_registry')
    )
    op.create_index(op.f('ix_projection_registry_tenant_id'), 'projection_registry', ['tenant_id'], unique=False)
    op.create_table('signal_definitions',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('definition_version', sa.String(length=30), nullable=False),
    sa.Column('transform_sql', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('online_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_signal_definitions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_definitions')),
    sa.UniqueConstraint('tenant_id', 'name', 'definition_version', name='uq_signal_def_version')
    )
    op.create_index(op.f('ix_signal_definitions_tenant_id'), 'signal_definitions', ['tenant_id'], unique=False)
    op.create_table('signal_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('definition_version', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('freshness', sa.String(length=20), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_signal_values_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal_values'))
    )
    op.create_index(op.f('ix_signal_values_tenant_id'), 'signal_values', ['tenant_id'], unique=False)
    op.create_index('ix_signals_lookup', 'signal_values', ['tenant_id', 'entity_type', 'entity_id', 'name'], unique=False)
    op.drop_index(op.f('uq_one_active_reservation_per_unit'), table_name='reservations', postgresql_where="((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CONFIRMED'::character varying])::text[]))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_one_active_reservation_per_unit'), 'reservations', ['asset_id'], unique=True, postgresql_where="((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'CONFIRMED'::character varying])::text[]))")
    op.drop_index('ix_signals_lookup', table_name='signal_values')
    op.drop_index(op.f('ix_signal_values_tenant_id'), table_name='signal_values')
    op.drop_table('signal_values')
    op.drop_index(op.f('ix_signal_definitions_tenant_id'), table_name='signal_definitions')
    op.drop_table('signal_definitions')
    op.drop_index(op.f('ix_projection_registry_tenant_id'), table_name='projection_registry')
    op.drop_table('projection_registry')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_index(op.f('ix_claims_entity_id'), table_name='claims')
    op.drop_index('ix_claims_entity_field', table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
