"""documents lifecycle, inventory conflicts, marketing assets

Revision ID: 7f28ccacdd76
Revises: c3f52aeda112
Create Date: 2026-09-26 21:21:11.236325

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f28ccacdd76'
down_revision: Union[str, None] = 'c3f52aeda112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_assets',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_marketing_assets_reviewer_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_marketing_assets_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketing_assets'))
    )
    op.create_index('ix_marketing_assets_status', 'marketing_assets', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_marketing_assets_tenant_id'), 'marketing_assets', ['tenant_id'], unique=False)
    op.create_table('document_approvals',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('fk_document_approvals_approver_id_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_approvals_document_id_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_approvals_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_approvals'))
    )
    op.create_index(op.f('ix_document_approvals_document_id'), 'document_approvals', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_approvals_tenant_id'), 'document_approvals', ['tenant_id'], unique=False)
    op.create_table('document_signatures',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_person_id', sa.Uuid(), nullable=True),
    sa.Column('signer_user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_signatures_document_id_documents')),
    sa.ForeignKeyConstraint(['signer_person_id'], ['people.id'], name=op.f('fk_document_signatures_signer_person_id_people')),
    sa.ForeignKeyConstraint(['signer_user_id'], ['users.id'], name=op.f('fk_document_signatures_signer_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_signatures_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_signatures'))
    )
    op.create_index(op.f('ix_document_signatures_document_id'), 'document_signatures', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_signatures_tenant_id'), 'document_signatures', ['tenant_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_versions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version', name='uq_doc_version')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_versions_tenant_id'), 'document_versions', ['tenant_id'], unique=False)
    op.create_table('inventory_conflicts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('canonical_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('external_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_precedence', sa.String(length=60), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['property_assets.id'], name=op.f('fk_inventory_conflicts_asset_id_property_assets')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_inventory_conflicts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_conflicts'))
    )
    op.create_index('ix_inv_conflicts_open', 'inventory_conflicts', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_conflicts_asset_id'), 'inventory_conflicts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_inventory_conflicts_tenant_id'), 'inventory_conflicts', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_assets_fts'), table_name='property_assets', postgresql_using='gin')
    op.drop_column('property_assets', 'search_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_assets', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, (((((((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE((location ->> 'city'::text), ''::text)) || ' '::text) || COALESCE((location ->> 'area'::text), ''::text)) || ' '::text) || COALESCE((location ->> 'compound'::text), ''::text)))", persisted=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_assets_fts'), 'property_assets', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_inventory_conflicts_tenant_id'), table_name='inventory_conflicts')
    op.drop_index(op.f('ix_inventory_conflicts_asset_id'), table_name='inventory_conflicts')
    op.drop_index('ix_inv_conflicts_open', table_name='inventory_conflicts')
    op.drop_table('inventory_conflicts')
    op.drop_index(op.f('ix_document_versions_tenant_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_signatures_tenant_id'), table_name='document_signatures')
    op.drop_index(op.f('ix_document_signatures_document_id'), table_name='document_signatures')
    op.drop_table('document_signatures')
    op.drop_index(op.f('ix_document_approvals_tenant_id'), table_name='document_approvals')
    op.drop_index(op.f('ix_document_approvals_document_id'), table_name='document_approvals')
    op.drop_table('document_approvals')
    op.drop_index(op.f('ix_marketing_assets_tenant_id'), table_name='marketing_assets')
    op.drop_index('ix_marketing_assets_status', table_name='marketing_assets')
    op.drop_table('marketing_assets')
    # ### end Alembic commands ###
